### ISSUE TITLE
Feature Request: Hotkey or button to jump to the active note's position on the calendar

### ISSUE THREAD

**Issue by obsidianspear** [srg-kostyrko/obsidian-journal#27]
Thank you for the ability to quickly move forward and back between **existing notes** across **different time frames** (daily, weekly, monthly, quarterly, yearly) using the same hotkey based on what's opened. If there are gaps in my calendar, it likely means there wasn't anything important to note, thus this feature is a game-changer compared to the functionality of other calendar-dedicated and core Daily Note plugins already. You have my gratitude. 

## One change I would love to see: 
Simply put: ```A hotkey and/or button to highlight and show the "currently open note" on the calendar, supporting all time frames.```

### _Some thoughts:_
- This allows one to visually see relevant entries based on what is **currently opened**.
- Easily jump to the quarter or year view by presenting the **first month of that period** on the calendar (since they go beyond the monthly calendar). 
- A simple slow highlight fade in and out after jumping would be appreciated, but not required. With `show on calendar`, Daily jumps to month and highlights day, of course. Weekly could highlight the entire week and fade away. Month, quarter, and yearly jumps highlight the entire calendar quickly.

### _Workflow Example:_
- Open the current weekly note.
- Navigate to previous weeks. Now currently in a weekly note from a few months ago.
- Hit "Show on Calendar" to open the relevant month and highlight the currently opened week on the calendar.
- See the days of that week, including if they had notes or not, as well as the month, quarter, and year at a glance.
- Click "Show Today" to jump back to the present.

All of this in mere seconds. Quick. Easy. Simple. 

---
## Extended Functionality (not a priority):
> Not what I'm asking for, but additional ideas. The above is already more than enough to see benefits.
- Hotkeys to navigate up and down the time frame hierarchy based on the active note (e.g., from daily to weekly, weekly to monthly, etc.). It can also be referred to as zooming in and out.

This could potentially be implemented in one of the following ways as options if it doesn't exist (based on what's currently opened and active): _When attempting to move up or down timeframes based on the current note..._
1. Prompt the user with "___ doesn't exist. Would you like to create a new note?" if the desired time frame doesn't have an existing note.
2. Automatically create a new note for the desired time frame if one doesn't exist without prompting.
3. If a valid note isn't opened and active, do nothing.

Coupled with the ability to navigate back and forth between existing entries with keyboard only, whew. It would simply feel incredible to fly through the calendar. Not necessary, but just a thought. I am not experienced enough in coding, so I humbly request the main feature above. Thank you for all you've contributed thus far! Sorry if this is more convoluted than it needs to be.

**Comment by srg-kostyrko** [comment]
thank you for feedback and ideas
zoom in/out is really great idea - will definitely add it

A have a question re open in calendar functionality
I was considering to auto adjust calendar view based on active note - so if you opened a note several months in path calendar view will automatically switch to that month. This way no additional hotkeys needed. On other hand calendar that is not adjusting might be good as well - you have control which month is is there and with hotkeys can quickly switch.
Would like to hear your opinion on what makes more sense for you

**Comment by obsidianspear** [comment]
Hello, thank you for your consideration. In my opinion, auto-adjusting the calendar to reflect the active note sounds more intuitive. I only assumed you had your reasons for this and wanted to request additional functionality. That would be much simpler to implement 🙂

**Comment by srg-kostyrko** [comment]
Great, I'll add this in next release

**Comment by srg-kostyrko** [comment]
Released in 1.3.0
