### ISSUE TITLE
[BUG]  journals with negative journal-interval-index are created  before  time  visible in caldendar before start date

### ISSUE THREAD

**Issue by danieltomasz** [srg-kostyrko/obsidian-journal#28]
Great plugin, I am switching to it from periodic notes :) 
I want to create a custom weekly  journal  with the data starting from today (or any other day) and I have active calendar journals.

The coustom journals are created for preceding time for all the times they are visible in the calendar, so I can have custom-journal -1, custom-journal -2, et cetera

![image](https://github.com/srg-kostyrko/obsidian-journal/assets/7980381/44b1968d-4737-4bdb-8fa6-ff1fb3d7481e)
I only want to have  journals starting from 1

I am on Obsidian 1.5.11 and MacOS

**Comment by danieltomasz** [comment]
Expected behaviour - the  journal notes should  not be created for period before start;
Also but this might be a FR - there should be a stop date that could be defined in settings for such calendar.

**Comment by srg-kostyrko** [comment]
good point, I missed this somehow, will fix so that for interval journals with increasing index there won't be 0 and negative numbers. (I don't want to just limit by start date for cases then you start journaling not with index 1 you might still want go back till 1)

**Comment by danieltomasz** [comment]
hi @srg-kostyrko thank for looking into it!
I (someone) might want to have a journal with dates (no numbers) and still  retain this behaviour;
For example the number is not important but I want this journal to be weekly meetings about a project that spans only specific time (like 3 or 6 months) and I want to quickly find a note from specific data, the order of meetings/notes is not important for me

But returning to the initial issue, could it be solved via  additional toggle in the settings  (like "strict enforce starting (and closing if you implent it) date(s)")? Or "Limit note creation by starting date"); 
I will create another feature request to ask about ending date :) 

This way you will also get consistent behaviour independently from naming convention, which might be more intuitive to user and cover more cases

**Comment by srg-kostyrko** [comment]
yeh that's a good point
than I'll add a toggle to limit journal entries by start and dates

**Comment by srg-kostyrko** [comment]
released in 1.3.0
