### ISSUE TITLE
[BUG]: Code blocks — Note is not connected to a journal

### ISSUE THREAD

**Issue by Lisandra-dev** [srg-kostyrko/obsidian-journal#3]
I configured the plugin, the ribbon command works but when I try to insert 
```calendar-nav

```

I have the message "Note is not connected to a journal" 

What is the problem here?
![image](https://github.com/srg-kostyrko/obsidian-journal/assets/30244939/c4bbb622-a0bd-4e0b-bfdc-d935997a9ec9)
![image](https://github.com/srg-kostyrko/obsidian-journal/assets/30244939/28597a1c-35b3-4eaa-8261-7d4ef04d6fbd)

**Comment by Lisandra-dev** [comment]
Okay, I found the problem : when creating the note, the frontmatter is not added in the note, it's added as plaintext.

**Comment by srg-kostyrko** [comment]
I have rechecked and don't see any issues - note related data is added to frontmatter
it sounds like some other plugin is interfering
do you probably have some templating plugin?

**Comment by Lisandra-dev** [comment]
Yeah, I had template.

**Comment by srg-kostyrko** [comment]
hm, I tried installing templater but still cannot get frontmatter as plaint text
Is templater configured for you to work with folder where daily note is created?
is template being applied?

**Comment by Lisandra-dev** [comment]
Yes!

**Comment by srg-kostyrko** [comment]
looks like some kind of timing issue where 2 updates conflict
because for me template is not applied at all
I'll play around and try to find a solution

**Comment by srg-kostyrko** [comment]
I released 1.0.1 version - please give it a try to see if it solves problem for you

**Comment by srg-kostyrko** [comment]
@Lisandra-dev were able to check if issue is gone in latest version?

**Comment by Lisandra-dev** [comment]
Yup, work like a charm!
