### ISSUE TITLE
[FR] Allow for  adding an  end date (or number of repetition) when creating an  interval-based journal

### ISSUE THREAD

**Issue by danieltomasz** [srg-kostyrko/obsidian-journal#30]
Someone might want a journal that spans only specific period in a year (for example study semester) or have specific number of repetion (similar way like repeated events are created in google calendar)

![image](https://github.com/srg-kostyrko/obsidian-journal/assets/7980381/23663bbc-9a38-412e-ba07-9ef9fb32a723)

**Comment by danieltomasz** [comment]
Currently `journal-start-date` mean something else - in the 1.2 `journal-start-date` or `journal-end-date` mean more like this specific note `note-start-date` or `entry-start-date`;

What I meant by  journal start date is current `journal-end-date` or start date of first entry, by `journal-end-date` I mean end date of last entry in this journal

**Comment by srg-kostyrko** [comment]
Released in 1.3.0
