### ISSUE TITLE
Can't create more then two journals

### ISSUE THREAD

**Issue by NRVB** [srg-kostyrko/obsidian-journal#36]
Hi I have an issue, can't create more then two journals. When adding a third one the "oldest" one dissappears. Does anyone know what I might be doing wrong or is it a bug?

**Comment by srg-kostyrko** [comment]
I played around and most likely you don't use unique ID when creating new journals. 
I'll add checks to warn about this in next version to avoid confusion but for now just make sure to use different IDs when creating new journal.

**Comment by srg-kostyrko** [comment]
ID is used to tell different journals (that usually means different configs) apart
