### ISSUE TITLE
Inconsistent "Folder" setting

### ISSUE THREAD

**Issue by Cito** [srg-kostyrko/obsidian-journal#4]
I noticed that the "Folder" setting works differently for calendar and interval based journals. For calendar based journals, this folder is interpreted as relative to the folder configured in the core daily notes plugin, whereas for interval based journals, it is relative to the root path. Is this difference intended? If yes, it would be helpful to mention it on the settings page.

**Comment by srg-kostyrko** [comment]
Calendar based journals have additional setting `Root folder` and section(daily, weekly etc.) folders are relative to it. Maybe in your case that root folder is the same as  folder configured in the core daily notes plugin and that is why it looks like it took settings from core plugin.

I'll add more details to folder setting description for clarity.

**Comment by Cito** [comment]
Thanks - you're right, that was in fact the case. I overlooked it because the Root folder setting is not part of the same dialog, but in the parent dialog. If you just add some words about this where the Folder setting is shown, this would be sufficient.

**Comment by srg-kostyrko** [comment]
Yeh that will be done in https://github.com/srg-kostyrko/obsidian-journal/issues/8
