### ISSUE TITLE
Allow vault-wide locale adjustment setting

### ISSUE THREAD

**Issue by arnoesterhuizen** [srg-kostyrko/obsidian-journal#42]
When I enable the [Calendar plugin](https://github.com/liamcain/obsidian-calendar-plugin), there is a setting to override the vault locale.

Not all the devices I use have a consistent locale, and being able to configure locale settings in a consistent manner is very useful. This might be a task for a different plugin, so feel free to decline this request.

**Comment by srg-kostyrko** [comment]
While changing week start seems to be needed as part of this plugin (as you sometimes want it be different from locale settings) changing whole locale seems something that not a part of plugin. So I won't be adding it to plugin for now.
