### ISSUE TITLE
Format calendar to 3 characters instead of full month

### ISSUE THREAD

**Issue by mtissington** [srg-kostyrko/obsidian-journal#45]
How can I change the format of the calendar month to just 3 characters instead of the default full month?

In other words from MMMM to just MMM

**Comment by srg-kostyrko** [comment]
Could you describe why you need such change? 
For now calendar date formats are not configurable as I did not see a use case for it.

**Comment by mtissington** [comment]
There are multiple situations when the calendar just fits in the right panel width. Then a longer month is displayed and now there is no gap between the month and the year - `December2023` 
If all the months were abbreviated to 3 characters `MMM` then the view would remain consistent.

**Comment by srg-kostyrko** [comment]
I see, I'll play with styling to prevent such display and still keep long names

**Comment by mtissington** [comment]
great - the styling is a bit off elsewhere - if I increase the width of the right side bar, the calendar stays on the left at a fixed width but the header expands to full width of side bar.

**Comment by srg-kostyrko** [comment]
Improvements released in 1.4.0
