### ISSUE TITLE
Inteval based journal keep re-creating already  created entries in old location, even  after changing folder location

### ISSUE THREAD

**Issue by danieltomasz** [srg-kostyrko/obsidian-journal#49]
1)  I created a custom journal within folder A and created there an  entry
2) I changed the location of jornal to folder B
3) New notes are created in folder B, but the 1 note that was already created, keeps appearing in folder A, even if I delete it/move it

**Comment by srg-kostyrko** [comment]
Thanks for reporting, will fix it in next release
A workaround for now would be
- delete note in folder A
- close Obsidian
After opening it should create that note in folder B

**Comment by srg-kostyrko** [comment]
Issue fixed in 1.4.0
