### ISSUE TITLE
Document relationship with core plugin

### ISSUE THREAD

**Issue by Cito** [srg-kostyrko/obsidian-journal#5]
Currently it is not clear to me whether this plugin is meant to completely replace the core daily notes plugin (i.e. should I switch it off?) or to work in conjunction with it (i.e. should be kept switched on?).

I'd like to switch the core daily notes plugin off, but then I lose the core commands "open previous daily note" and "open next daily note", which are different from Journal commands "open yesterday's note" and "open tomorrow's note" in the case there are gaps. As mentioned in issue #4, it looks like the core plugin settings are used.

However, when I keep the core plugin switched on, then I have this unnecessary icon that, when clicked, will create a daily note without the metadata required by the Journals plugin.

Would be helpful if you clarify how this is intended to work and whether it is recommended to switch the core plugin off or not.

**Comment by srg-kostyrko** [comment]
Yeh this plugin is mean to be a replacement for Daily notes and it is better to switch that one off (as you noticed notes created through Daily notes is not properly connected to a journal).

I've created an issue https://github.com/srg-kostyrko/obsidian-journal/issues/9 to add a command that will work similar to Daily notes.

I also updated Readme with info how this plugin works with others.

**Comment by Cito** [comment]
Thank you!
