### ISSUE TITLE
Weekly Journal entry pulling daily template

### ISSUE THREAD

**Issue by gusreid** [srg-kostyrko/obsidian-journal#50]
![Obsidian_3NcKVNsUhO](https://github.com/srg-kostyrko/obsidian-journal/assets/145200163/03642377-86f9-4ca1-9e58-ef0d869066c0)

I just installed and set up Journals plugin. 
I love it and it seems to work really well... 
except...
When I create a weekly or yearly note it pulls in my daily template. 
Quarterly works fine. 

It's likely something I'm doing as I'm very new to techy stuff and I'm an old man!

Any ideas? 

My settings seem correct. See screenshot. 
![Obsidian_F6y98ygtyW](https://github.com/srg-kostyrko/obsidian-journal/assets/145200163/78c5b7e3-c57b-4f29-a9fe-14824a510ea7)

**Comment by srg-kostyrko** [comment]
hm configs are kinda separate so this should not happen
could you provide more details
- do you have Templater plugin? if yes - please check that you don't have template for folder configured
- does it happen for any way that you create new note (like command/calendar/navigating through code blocks)?

**Comment by gusreid** [comment]
Ah yes, it was the Templater thing. I added the folders and their corresponding templates and it has fixed the issue. Many thanks. Great plugin!
