### ISSUE TITLE
[Discussion] Rethinking Journals concept

### ISSUE THREAD

**Issue by srg-kostyrko** [srg-kostyrko/obsidian-journal#54]
The more I work with journals thee more I get the feeling that having 2 journal types (calendar vs interval) was not a good idea.
Partially I did it because I was working of Periodic Notes plugin. Even at that point it seemed not right but I did not see a better way at that moment.

After some considerations I plan to remove this dichotomy and have just one concept:

A `journal` is set of notes that you write on regular basis - daily, weekly, monthly or some custom period (like every 2 weeks).

For current concepts this means:
- `Calendar journal` - will be split into separate journal for every period
- `Interval journal` - will be a journal with custom period of writing

To compensate for some calendar journal functionality I plan to also add a concept of `journal group` (for example `work` or `personal`)  - that will allow to have focused calendar view for just work related journals for example.

As this is quite a big of a change I plan to make it a major plugin release.
Settings and data migration will be done automatically on first plugin start after update.

I would like to hear feedback. concerns or ideas from anyone using this plugin

**Comment by arnoesterhuizen** [comment]
I like the simplified view you propose: intervals are just intervals, and a calendar is just a set of intervals we've internationally agreed on.

I don't see the value for journal groups yet. wouldn't using existing tags be enough to meet the filtering requirement?

**Comment by srg-kostyrko** [comment]
Good question

I got an idea of journal group when I was thinking on how to keep same functionality in `calendar-nav` and `calendar-timeline` blocks.
There you can get not only to current level (like daily) but to other notes within same calendar (like weekly, monthly or yearly notes) given they are active.
As there will be no such direct connection we should somehow connect journals in other way. If you are using just one set of connected journal - you might not even need groups. But for people who have work vs personal journals combining everything in code blocks might be not convenient.
Focused calendar view was a further idea on how to use groups.

In some sense  you are right - groups are similar to tags just on journal level. But I wanted to avoid confusion as it might not fully work as regular tag - for example I don't see a way to make it searchable 

If you have any other idea on how to change code blocks with new journal concept - please let me know

**Comment by arnoesterhuizen** [comment]
I want to make sure I understand what you are proposing:

# Option 1

1. A user will add a journal in the plugin settings, but instead of choosing a type, they will be able to check **all the intervals** they want to add:
    1. Yearly, quarterly, monthly, weekly, daily, and/or a custom interval like every `x` weeks starting 2024-07-12
    2. intervals could be stored using a format like https://en.wikipedia.org/wiki/ISO_8601#Durations
1. The `journal` ID and `journal-section` will then be added in the frontmatter as usual
2. Code blocks like the following would be used to navigate the journals

```markdown
    ```calendar-timeline
    journal-section: [one of: year | quarter | month | week | day | interval]
    journal: [journal ID]
    ```
```

or

# Option 2

1. A user will add a journal in the plugin settings, but instead of choosing a type, they will be able to **select a single interval** they want to add:
    1. Yearly, quarterly, monthly, weekly, daily, or a custom interval like every `x` weeks starting 2024-07-12
    4. intervals could be stored using a format like https://en.wikipedia.org/wiki/ISO_8601#Durations
1. A `journal-group` to connect the various intervals, as well as a `journal` ID and `journal-section` will be added to the frontmatter
2. Code blocks like the following would be used to navigate the journals

```markdown
    ```calendar-timeline
    journal-group: [month or year or interval]
    journal: [journal ID]
    journal-section: [not used anymore?]
    ```
```

or something completely different?

**Comment by arnoesterhuizen** [comment]
Using option 1 would move the journal type `interval` as a sub-option inside the current journal configuration, instead as a sibling, e.g.
 
![Screenshot_20240712_144636_Obsidian~2](https://github.com/user-attachments/assets/9c2bc602-8ed8-4977-a151-5a74ce479be3)

**Comment by srg-kostyrko** [comment]
It is option 2 - for example instead one journal for daily and weekly notes there will be 2 separate journals

as for frontmatter 
- journal-section would be removed as obsolete (it was needed before because one journal might have several different sections active at the same time)
- not sure about adding group as plugin can read it from config (but might be handy for queries probably)

code blocks will probably be renamed but ability to set what group or journal should be used will definitely be there

also as part of journal unification functionality that currently is only in interval journals will be avaliable for every journal - like start date, journal end (specific date or after some number of repetitions) and indexing

**Comment by arnoesterhuizen** [comment]
I feel that option 1 might be easier to understand for end-users, easier to design from an interface perspective, and it aligns better with the way the plugin already works, so less migration steps.

The plugin already makes provision for adding different sections to a journal, so adding a `custom` interval would just be another toggle switch with a configuration screen behind that. Grouping is then already built in (via the journal ID), and you'd need to do less to migrate -- less frontmatter properties to add/change.

With option two, I feel there is more risk of end-users misunderstanding how the grouping works, and additional places for user error if you have to fill in the `journal-group` for each journal. Then, updating the interface to somehow show the journals connected to the same group adds a layer of complexity.

Either option would need the same amount of work in the back-end, I suspect, so I'd vote for option 1 as being more user-friendly.

**Comment by arnoesterhuizen** [comment]
Interface mockup for option 1: 

After adding a new journal, a toggle is added for a custom interval:

![Screenshot 2024-07-12 162105](https://github.com/user-attachments/assets/23307b80-790e-4bde-91e8-86dc6714bbdd)

Settings for Custom interval notes already exist:

![Screenshot 2024-07-12 162134](https://github.com/user-attachments/assets/5e866e36-1743-4850-9aa6-4c80b0338179)

**Comment by srg-kostyrko** [comment]
Hm, good point I did not think that way

Though for more flexibility custom intervals should be probably not as toggle but with possibility to add multiple custom intervals 

And maybe changing regular intervals (daily, weekly etc) to be added not as toggle as well - in case someone wants to have multiple writing intervals but not default ones

**Comment by Volker-brdb** [comment]
I would favor option1

**Comment by hummelriegel** [comment]
Maybe I do not get your full use case here, but:
* I agree that "interval" represents calendar as well as customized intervals. Assuming that adding manual "irregular" notes are still possible (e.g. notes on your sports sessions), that covers everything I can think of.
  * Following the proposed ISO 8601 standard would give maximum flexibility. You could keep the "daily", "weekly" ones in the UI for better UX, but technically it wouldn't be needed.
  * You could even think about support for shorter intervals (e.g. hourly) to track, for example, medical symptioms. Possibly a future feature.
* I don't understand why a single journal needs multiple intervals. I would most likely just create two journals then.
  * Wouldn't having multiple notes and linking them later be one of the principles of knowledge management with obsidian or the "Zettelkasten" approach either?
* I can think of two scenarios of "grouping" journals:
  *  I want group/split thematically, e.g. "work", "leisure" or "sports": I can focus on my work notes during worktime and on leisure notes at the other times.
     * I also would see the tags as a perfect fit from user perspective. It is free-form and you could also assign notes to multiple ones, if needed. 
     * Alternatively, you could use the folder structure, of course. Less flexible, but possibly easier to understand. Not different from standalone notes.
  * I want to group by "interval": I want to see my "work" and "leisure" notes combined for the same day for my overall retrospective.
* Personally, I usually also consider statistical analyses. Using the notes to keep track of working hours, happiness, sports metrics, number of social interactions, could also be interesting for some users. While this is some sort of independent, I would assume that using the typical "date" or "datetime" in the frontmatter as well as the "tags", it might be quite compatible with most of the other (statistical) plugins.

**Comment by srg-kostyrko** [comment]
Thanks everyone for discussion. 
I'm starting work on v2 and will be changing journal concept as described.
Journal shelves (aka groups) will be used to group journals in settings (so it resembles current UI) and in calendar view/code blocks to limit what is shown.
I created a separate issue on v2 work - https://github.com/srg-kostyrko/obsidian-journal/issues/63
and a separate project to track progress - https://github.com/users/srg-kostyrko/projects/3
