### ISSUE TITLE
Document integration with Calendar plugin

### ISSUE THREAD

**Issue by Cito** [srg-kostyrko/obsidian-journal#6]
I liked to use daily notes together with Obsidian's [Calendar](https://github.com/liamcain/obsidian-calendar-plugin) plugin.

After switching from the core daily notes plugin to Journals, this still worked pretty well, except the feature that I can create a new note by clicking on an arbitrary date in the calendar.

It only works if the core daily notes plugin and the Journals plugin use the same file names and folders, the note is created, but the metadata header is missing. Only if I visit that note using a command from the Journals plugin, then the metadata is created.

Would be helpful if you could document this under "known issues" or a section "compatibility with other plugins" (like the core daily notes plugin and Calendar plugin). Maybe some of these issues can be also solved over time.

**Comment by srg-kostyrko** [comment]
I plan to add Calendar view similar to Calendar plugin - this way Calendar plugin will be not needed.

Please follow https://github.com/srg-kostyrko/obsidian-journal/issues/10 to see when it gets out.
