### ISSUE TITLE
How to display 'week' in 'calendar-nav'?

### ISSUE THREAD

**Issue by Morganwan90** [srg-kostyrko/obsidian-journal#65]
I see the view in the readme as:
![image](https://github.com/user-attachments/assets/4c13bf68-8abd-4943-9951-fae07d362f7f)

My current view is:
![image](https://github.com/user-attachments/assets/fbd46cd0-5efb-4dde-9402-575aa5af442f)

ps: “九月” means September
How can I change the month to 'week'?

**Comment by srg-kostyrko** [comment]
currently week number is displayed only if you enable weekly notes in the journal
I plan to make this block highly configurable in v2

**Comment by Morganwan90** [comment]
> currently week number is displayed only if you enable weekly notes in the journal I plan to make this block highly configurable in v2

Got it ! thanks a lot!
