### ISSUE TITLE
Clicking on a Week Now goes to previous week

### ISSUE THREAD

**Issue by josh-smartx** [srg-kostyrko/obsidian-journal#76]
## Description
I upgraded to version 1.4.2 today and found that when clicking on a week to create a weekly note, it opened the previous week's note.
Example: I clicked on W43 on the calendar view and it opened Week 42's note. 

I've been able to get around this bug by modifying my default date format for my weekly note to `[Week] ww+1` . This had been working in the previous version I had installed, so I believe this bug was introduced in v1.4.2.

**Comment by srg-kostyrko** [comment]
I tried to reproduce this issue and I cannot - calendar view correctly navigates for me
have you recently made any changes to other settings? first date of week probably?
could you provide screenshot of properties for W42 and W43 notes

**Comment by josh-smartx** [comment]
First day of the week is set to Sunday. I'm beginning to think it may be related to files not created by the plugin aren't working properly. Trying W44 works properly, so I will just have to be careful when looking at previous data. 

Thank you for looking at this and thank you for the plugin, it's awesome 😄 . I'm closing this issue as its not a problem

**Comment by srg-kostyrko** [comment]
It might be that journal data in note frontmatter were wrong for some reason and as result note title differs from what journal assumes that note to be connected to.
