### ISSUE TITLE
Weeks offset by one

### ISSUE THREAD

**Issue by Man-at-Arms46** [srg-kostyrko/obsidian-journal#81]
When navigating via the calendar or nav, the weekly note is now being offset by one week (regardless of note name or change to start of week, using Sunday or Monday, and even turning Templater off).  Assuming it is referencing a note file, regardless of note name, I have even gone so far as to delete out those weekly notes so as to allow new weekly notes to be created (then pasting back in the prior contents).

While this seemed to be a momentary workaround, the activity has started again.  Each time the offset overwrites the dates in my frontmatter, using the prior week's.  As i use dataview to summarize the week based upon those frontmatter dates, it means my weekly notes are becoming jumbled.  
 
![image](https://github.com/user-attachments/assets/864eabd5-7d2c-4778-a6ae-294bfa59404e)
![image](https://github.com/user-attachments/assets/a569150e-8195-49d2-bb0a-d4de5bba1cb3)

**Comment by srg-kostyrko** [comment]
I tried reproducing it - and it works for me
if I understand correctly from your screenshots - note title is wrong (2024-11-03 is W45)
could you please show your weekly settings?
and have you recently changed week start date or how first week of year is calculated?

**Comment by Man-at-Arms46** [comment]
Thanks for the reply!
Weekly settings image below: the issue showed up before i changed any weekly settings (i tried to play around with it afterwards, to see if i could get it to offset, but no different)

When the note was created, it appeared to be linked to the right week (both name & date in frontmatter).  When I use the calendar or nav selector to roll through weeks, for some reason it starts jumping to a file that is a week off, then overwriting the date in frontmatter (in the pic above: clicking W45 in the calendar now jumps to 2024-W44 note and overwrites the date; 2024-W44 frontmatter was originally 10/27 to 11/2. Even when i manually change it back to those dates, the calendar selector overwrites it to match a week off). 


![image](https://github.com/user-attachments/assets/e4335c3f-3c7e-495e-b0b1-b58d4ff3dcec)
![image](https://github.com/user-attachments/assets/cd89e7d1-efec-427a-a131-f5a69c16086b)

**Comment by srg-kostyrko** [comment]
The problem is with your date format 
`WW` is ISO based numbers (with week starting on Monday and first week of year to be the one that has 4 days)
so it is not taking plugin settings into account
and with plugin using Sunday as first day of week and first week to be the one with 1st January leads to numbering difference
use `ww` instead - this option will be using plugins settings
I should probably add some validation to weeks formatting to avoid such confusion in future

**Comment by Man-at-Arms46** [comment]
Thank you so much for the patience-- that seemed to work!  I changed to lower case "ww" in the setting, deleted the old weekly notes & then recreated.  Now, when scrolling through them, it no longer appears to jump and overwrite one week off, the way it was doing.  
I greatly appreciate your help as i have found the plugin to be so useful with the addition of a weekly note.  That allows me to quickly reference back periods in order to summarize trends, which is why it was frustratingly disorienting when shifting a week off (used the weekly frontmatter dates to run a dataview query summarizing a figure from that week's daily notes; original images update to how they appear now)

![image](https://github.com/user-attachments/assets/e90db7b2-24c6-41e0-a1aa-7dde68428fdf)
![image](https://github.com/user-attachments/assets/709b5fd6-88e2-4a9b-8fb3-30d79e0aed59)
![image](https://github.com/user-attachments/assets/8ceebb5f-494d-4011-924e-2916f7c98aa8)

**Comment by srg-kostyrko** [comment]
Glad to hear that it is resolved.
