### ISSUE TITLE
No New Note Creation on IPad

### ISSUE THREAD

**Issue by loupage** [srg-kostyrko/obsidian-journal#84]
I am using Obsidian on an iPad running iPadOS 18.2. 
- No new note is created when I click on Today
- No new note is created when I click on a specific day
- No new note is created if I try to navigate to a day where there is no note.

All works as expected if the daily note already exists.

Any workarounds?

**Comment by srg-kostyrko** [comment]
I've tried on iPadOS 17 and it works without issues for me
could you please provide text that you get when opening Command pallet and selecting Show debug info command
and is it only Calendar view? or commands as well?

**Comment by loupage** [comment]
Here is the debug info you requested:SYSTEM INFO:	Operating system: ios 18.2 (Apple iPad13,4)	Obsidian version: 1.7.7 (172)	API version: v1.7.7	Login status: logged in	Language: en	Catalyst license: insider	Live preview: off	Base theme: dark	Community theme: Minimal v7.7.10	Snippets enabled: 1	Restricted mode: off	Plugins installed: 12	Plugins enabled: 12		1: Dataview v0.5.67		2: Callout Manager v1.1.0		3: Charts v3.9.0		4: Heatmap Calendar v0.7.1		5: Tracker v1.14.0		6: Style Settings v1.0.9		7: Minimal Theme Settings v8.1.1		8: Contribution Graph v0.10.0		9: Excalidraw v2.6.8		10: Peerdraft v2.10.3		11: Templater v2.9.1		12: Journals v1.4.3RECOMMENDATIONS:	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.—-LouOn Dec 16, 2024, at 11:03 AM, Sergii Kostyrko ***@***.***> wrote:﻿
I've tried on iPadOS 17 and it works without issues for me
could you please provide text that you get when opening Command pallet and selecting Show debug info command
and is it only Calendar view? or commands as well?

**Comment by srg-kostyrko** [comment]
It is pretty much the same except for list of plugins (and OS version) - as I don't use Obsidian on ipad on regular bases it has only Journals for now
I see you use templater plugin - do you have any templater code in templates used by Journals?

**Comment by loupage** [comment]
I tried using a template with NO templater code, and had the same result.I had an older iPad running iPadOS 17 and it works with no problem.Here is the debug info:SYSTEM INFO:	Operating system: ios 17.5.1 (Apple iPad7,3)	Obsidian version: 1.7.7 (172)	API version: v1.7.7	Login status: logged in	Language: en	Catalyst license: insider	Live preview: off	Base theme: dark	Community theme: Minimal v7.7.10	Snippets enabled: 1	Restricted mode: off	Plugins installed: 12	Plugins enabled: 12		1: Templater v2.9.1		2: Dataview v0.5.67		3: Journals v1.4.3		4: Callout Manager v1.1.0		5: Charts v3.9.0		6: Heatmap Calendar v0.7.1		7: Tracker v1.14.0		8: Style Settings v1.0.9		9: Minimal Theme Settings v8.1.1		10: Contribution Graph v0.10.0		11: Excalidraw v2.6.8		12: Peerdraft v2.10.3RECOMMENDATIONS:	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.Sent from my iPadOn Dec 16, 2024, at 11:22 AM, Sergii Kostyrko ***@***.***> wrote:﻿
It is pretty much the same except for list of plugins (and OS version) - as I don't use Obsidian on ipad on regular bases it has only Journals for now
I see you use templater plugin - do you have any templater code in templates used by Journals?

**Comment by loupage** [comment]
The good news is that it is working!  The bad news is that I am not quite sure why.I started with a very plan daily template that worked.  Then I built out the rest of the template, testing each section as I went. And… it is currently working.Keeping my fingers crossed, —-LouOn Dec 16, 2024, at 12:46 PM, Lou ***@***.***> wrote:﻿I tried using a template with NO templater code, and had the same result.I had an older iPad running iPadOS 17 and it works with no problem.Here is the debug info:SYSTEM INFO:	Operating system: ios 17.5.1 (Apple iPad7,3)	Obsidian version: 1.7.7 (172)	API version: v1.7.7	Login status: logged in	Language: en	Catalyst license: insider	Live preview: off	Base theme: dark	Community theme: Minimal v7.7.10	Snippets enabled: 1	Restricted mode: off	Plugins installed: 12	Plugins enabled: 12		1: Templater v2.9.1		2: Dataview v0.5.67		3: Journals v1.4.3		4: Callout Manager v1.1.0		5: Charts v3.9.0		6: Heatmap Calendar v0.7.1		7: Tracker v1.14.0		8: Style Settings v1.0.9		9: Minimal Theme Settings v8.1.1		10: Contribution Graph v0.10.0		11: Excalidraw v2.6.8		12: Peerdraft v2.10.3RECOMMENDATIONS:	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.Sent from my iPadOn Dec 16, 2024, at 11:22 AM, Sergii Kostyrko ***@***.***> wrote:﻿
It is pretty much the same except for list of plugins (and OS version) - as I don't use Obsidian on ipad on regular bases it has only Journals for now
I see you use templater plugin - do you have any templater code in templates used by Journals?
