### ISSUE TITLE
Opening new entry moves cursor inside calendar-nav codeblock on macOS

### ISSUE THREAD

**Issue by anarqist** [srg-kostyrko/obsidian-journal#86]
Hi,

when I add a new note (doesn't matter if daily, weekly, monthly, yearly) it always puts the cursor inside the code block for calendar-nav.

I have to manually click somewhere else, below, to exit that code block and be able to actually write something. 

This does not apply to my iPad. 
It also does not help to add additional text as well below the codeblock in my template, it always adds the cursor inside the code block.

**Comment by anarqist** [comment]
You can also see the behaviour on this [video](https://inv.nadeko.net/watch?v=ks969Cp0yZU) (not filmed by me) at around 4:05mins ongoing.

**Comment by srg-kostyrko** [comment]
plugin does not manage how exactly editor opens file.
usually cursor is put on the first line of a note
and if first line you have is code-block - it automatically goes into editing
there are 2 approaches possible here:
- if you use templater plugin you can use `<% tp.file.cursor() %>` to set cursor to specific place in your template
- you can add empty line before first code block (so cursor when set to first line in note does not touch code block)

**Comment by anarqist** [comment]
Thx for explanation. that helps to understand the system behind the scenes a bit better. 

Using templater is awesome for that purpose. Thank you very much!
