### ISSUE TITLE
Improve support for data.format

### ISSUE THREAD

**Issue by brianmd** [srg-kostyrko/obsidian-journal#89]
Rather than dump all journal daily notes into a single directory, it'd be nice to be able to separate them into folders such as:

- Daily/{{date.format("YYYY")}}/{{date.format("MM")}}

{{date}} does do the evaluation prior to folder creation, but date.format does not seem to.

**Comment by srg-kostyrko** [comment]
formatting in variables works a bit differently - there is no `data.format`
instead you can just put format after colon without quotes
so for your example it will be
```
Daily/{{date:YYYY}}/{{date:MM}}
```

**Comment by brianmd** [comment]
That works beautifully! Thank you.
