### ISSUE TITLE
Error applying templater w: Invalid reference date format.

### ISSUE THREAD

**Issue by MMoMM-org** [srg-kostyrko/obsidian-journal#90]
Any idea what is causing this?
Result is journals properties are in the note and the template ist also in the note.
Running replace templates in file works without any issues.
This happens for all my templates except the daily one

Code in question is here: https://github.com/srg-kostyrko/obsidian-journal/blob/46296a208b6af2b0d9f4502ee7f36d4c2036f360/src/utils/template.ts#L129

**Comment by srg-kostyrko** [comment]
this should be Templater plugin failing to process a template
when we talk about templater - journals plugin first processes its variables, and after that templater gets called
if it works in file - my guess would be that journals plugin processing variables somehow messes up the template causing templater to fail
will you be able to share some template that fails? so that I can dig deeper into it

**Comment by MMoMM-org** [comment]
sure.... but it is complicated 😄 
let me try to cut it down to the minimum... 
I think I found the issue.
while trying to cut the template down to a minimum I also run into the error in Templater directly
after changing the top part to do some other parsing I now run into the error
Cannot read properties... substring.

# New Code
```
let title = this.app.workspace.getActiveFile().basename
let [year, quarter] = title.split('-');
let quarterNum = parseInt(quarter.substring(1));
let date = new Date(year, (quarterNum - 1) * 3, 1);
let tq = tp.date.now("YYYY-[Q]Q", 0, date);
let pq = tp.date.now("YYYY-[Q]Q", "P-3M", date);
let nq = tp.date.now("YYYY-[Q]Q", "P+3M", date);
let ty = tp.date.now("YYYY", 0, date);
let lm = tp.date.now("YYYY-MM", "P+2M", date);
```

Changing the way to get the title to 
`let title = tp.file.title;`

Makes it work.

This is also the only change to make in the original template. 

# Original Template
```
<%*
// Alias:: 🗓️ Quarter
// #content/template
// #type/timeline/quarterly
let title = this.app.workspace.getActiveFile().basename
let path = await tp.user.j_getPathByNumber("304") +"/"
let weeklyPath = await tp.user.j_getPathByNumber("302")
let tq = tp.date.now("YYYY-[Q]Q",0, title, "YYYY-[Q]Q")
let pq = tp.date.now("YYYY-[Q]Q", "P-1M", tq, "YYYY-[Q]Q")
let nq = tp.date.now("YYYY-[Q]Q", "P+4M", tq, "YYYY-[Q]Q")
let ty = tp.date.now("YYYY",0, tq, "YYYY-[Q]Q")
try {
REMOVED A LOT TO PROTECT THE INNOCENT
```

**Comment by srg-kostyrko** [comment]
yeh the problem is definitely in 
```
let title = this.app.workspace.getActiveFile().basename
```
because the journals plugin processes a template before creating and opening a note
so active file won't be what you expect
will add this to the templater support description

**Comment by MMoMM-org** [comment]
strange thing though was that it did work for my day template... whatever.. nice plugin btw 😄
